{% set version = '1.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-microbiomestat
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MicrobiomeStat_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MicrobiomeStat/MicrobiomeStat_{{ version }}.tar.gz
  sha256: f851d71a008a768457a3c8ea797406dd03abfa1bcee4e33b01610e433532ecce

build:
  merge_build_host: True  # [win]
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-lmertest
    - r-mass
    - r-matrix
    - r-matrixstats
    - r-modeest
    - r-statmod
  run:
    - r-base
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-lmertest
    - r-mass
    - r-matrix
    - r-matrixstats
    - r-modeest
    - r-statmod

test:
  commands:
    - $R -e "library('MicrobiomeStat')"           # [not win]
    - "\"%R%\" -e \"library('MicrobiomeStat')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=MicrobiomeStat
  license: GPL-3.0-only
  summary: A suite of methods for powerful and robust microbiome data analysis addressing zero-inflation,
    phylogenetic structure and compositional effects (Zhou et al. (2022)<doi:10.1186/s13059-022-02655-5>).  The
    methods can be applied to the analysis of other (high-dimensional) compositional
    data arising from sequencing experiments.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: MicrobiomeStat
# Type: Package
# Title: Statistical Methods for Microbiome Compositional Data
# Version: 1.2
# Date: 2024-03-13
# Authors@R: c( person("Xianyang", "Zhang", role = "aut", email = "zhangxiany@stat.tamu.edu"), person("Jun", "Chen", role = c("aut", "cre"), email = "chen.jun2@mayo.edu"), person("Huijuan", "Zhou", role = "ctb"))
# Author: Xianyang Zhang [aut], Jun Chen [aut, cre], Huijuan Zhou [ctb]
# Maintainer: Jun Chen <chen.jun2@mayo.edu>
# Description: A suite of methods for powerful and robust microbiome data analysis addressing zero-inflation, phylogenetic structure and compositional effects (Zhou et al. (2022)<doi:10.1186/s13059-022-02655-5>).  The methods can be applied to the analysis of other (high-dimensional) compositional data arising from sequencing experiments.
# Depends: R (>= 3.5.0)
# Imports: ggplot2, matrixStats, parallel, stats, utils, Matrix, statmod, MASS, ggrepel, lmerTest, foreach, modeest
# NeedsCompilation: yes
# License: GPL-3
# Encoding: UTF-8
# Packaged: 2024-04-01 22:00:40 UTC; m123485
# Repository: CRAN
# Date/Publication: 2024-04-01 22:30:02 UTC
